sculpin_content_types:
  posts:
    enabled: false

sculpin:
  ignore: ['**/_*.scss']

sculpin_snappy:
  pdf:
    enabled: true
    options:
      margin_top: 0
      margin_right: 0
      margin_bottom: 0
      margin_left: 0
      no_outline: true
      disable-smart-shrinking: true
      no_pdf_compression: true
      print_media_type: true
